### ISSUE TITLE
Accessing the complete list of artists?

### ISSUE THREAD

**Issue by kyle-barry-apps** [art-institute-of-chicago/api-data#3]
Hi there,

Just wondering what the best way to access the complete list of artists would be. I'm looking to provide the list in a pre-propulated select field for a small app. Thanks in advance!

Best,
Kyle

**Comment by nikhiltri** [comment]
Hey @kyle-barry-apps,

There are about 13,000 artists in our API. The best way to get a complete list of all the artists would be to download the full dataset linked in this repo's README and parse through all the files in `json/agents`, looking for records with a value `is_artist` of `true`.

Thanks!
nikhil
