### ISSUE TITLE
404 images

### ISSUE THREAD

**Issue by iplanwebsites** [art-institute-of-chicago/api-data#4]
At least 30 images are returning 404.
Ex: https://www.artic.edu/iiif/2/0770255b-8aa5-41dc-9c06-3feb7a4c1f4f/full/843,/0/default.jpg

It is hard to detect since the `image_id` is provided as usual.
For at least 30 of these 404 images, the property `thumbnail.lqip `is set to `null`. ex:
 ```
 {
   "id": 221291,
   "title": "Paper Porcelain, Coffee Cup and Saucer Prototypes",
   "thumbnail": {
    "lqip": null,
    "width": 4881,
    "height": 3905,
    "alt_text": "A work made of cardboard and paper tape."
   },  
   "image_id": "30ab853e-57e1-faf1-4399-9f3975f8bdf6"
  }
  ```

**Comment by Foursharks** [comment]
I'm also having this issue - no images contain an image_id value.

**Comment by Foursharks** [comment]
If you query for 5 artworks, the 5th one and beyond seems to always have an id.

**Comment by nikhiltri** [comment]
Hey @iplanwebsites and @Foursharks,

My guess is this was a result of stale data. We just finished up some work updating the process that explores data to this repo and the tar.bz2 file linked in the README. I confirmed that all the records in [json/artworks](json/artworks) return a valid `image_id` that resolves in artic.edu/iiif/2/[image_id]. I took a look at the first handful of records in json/artworks in the tar.bz2 file and confirmed they are pointing to valid images as well. 

Let me know if you still run into trouble accessing valid images!

Thanks!
nikhil
